nix: attempt to fix tmpdir cleanup error for www
CI suddenly failing without changes related to the www package.

```
www> checking for references to /tmp/nix-build-www.drv-0/ in /nix/store/fxz6z5dfib33z9fmw640821qr57gligs-www...
www> patching script interpreter paths in /nix/store/fxz6z5dfib33z9fmw640821qr57gligs-www
error: cannot unlink "/tmp/nix-build-www.drv-0": Directory not empty
```

chatgpt-5.2-codex said this is due to the turbo daemon keeping the
tmpdir busy thus nix can't clean it up. Worth a try.